"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application Operational Mode: 'evaluation' (participant-facing / Railway) or 'feedback_lab' (researcher-facing / localhost)
APP_MODE = os.environ.get('APP_MODE', os.environ.get('APP_DATA_MODE', 'feedback_lab')).lower()
if APP_MODE not in ('evaluation', 'feedback_lab'):
    if APP_MODE == 'study':
        APP_MODE = 'evaluation'
    else:
        APP_MODE = 'feedback_lab'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*4q2uoa89hvwfy*43xgnt6bgd!k3hy)@*+p#q&6gp_p$7r1_o@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver,.railway.app').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://*.railway.app,http://localhost,http://127.0.0.1'
    ).split(',') if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'predictor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'predictor.context_processors.app_environment',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database Configuration:
# - Evaluation mode uses DATABASE_URL (Railway Evaluation PostgreSQL) or db_evaluation.sqlite3
# - Feedback Lab mode uses FEEDBACK_LAB_DATABASE_URL (Railway Feedback Lab PostgreSQL) or db.sqlite3
eval_database_url = os.environ.get('DATABASE_URL')
feedback_lab_database_url = os.environ.get('FEEDBACK_LAB_DATABASE_URL')
evaluation_database_url = os.environ.get('EVALUATION_DATABASE_URL')

if APP_MODE == 'feedback_lab':
    # Fail-closed guard: Feedback Lab requires explicit FEEDBACK_LAB_DATABASE_URL when using PostgreSQL.
    # Reject raw/unconfirmed DATABASE_URL to prevent accidental use of Evaluation DB.
    if eval_database_url and not feedback_lab_database_url:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "Database isolation violation: APP_MODE='feedback_lab' must not be configured "
            "with a production/evaluation DATABASE_URL. Feedback Lab requires local research storage or dedicated FEEDBACK_LAB_DATABASE_URL."
        )

    active_database_url = feedback_lab_database_url

    # Guard: Fail-closed if Feedback Lab is configured to use the known Evaluation PostgreSQL database
    if evaluation_database_url and active_database_url and active_database_url == evaluation_database_url:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "Database isolation violation: Feedback Lab cannot connect to the Evaluation database URL."
        )

elif APP_MODE == 'evaluation':
    active_database_url = eval_database_url

    # Guard: Fail-closed if Evaluation mode is configured to share the dedicated Feedback Lab database URL
    if feedback_lab_database_url and active_database_url and active_database_url == feedback_lab_database_url:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "Database isolation violation: Evaluation and Feedback Lab cannot point to the same "
            "production database URL. Separate databases are strictly required."
        )
else:
    active_database_url = feedback_lab_database_url or eval_database_url

if active_database_url:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(
                default=active_database_url,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    except ImportError:
        # Fallback if dj-database-url is not yet installed in local dev environment
        from urllib.parse import urlparse
        parsed = urlparse(active_database_url)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path.lstrip('/'),
                'USER': parsed.username,
                'PASSWORD': parsed.password,
                'HOST': parsed.hostname,
                'PORT': parsed.port or 5432,
            }
        }
else:
    # Inverse Safety Case: Ensure evaluation mode never falls back to development 'db.sqlite3'
    if APP_MODE == 'evaluation':
        raw_db_name = os.environ.get('DB_NAME', 'db_evaluation.sqlite3')
        if Path(raw_db_name).name == 'db.sqlite3':
            from django.core.exceptions import ImproperlyConfigured
            raise ImproperlyConfigured(
                "Database isolation violation: APP_MODE='evaluation' cannot use development "
                "database 'db.sqlite3'. Configure DATABASE_URL or use 'db_evaluation.sqlite3'."
            )
    else:
        raw_db_name = os.environ.get('DB_NAME', 'db.sqlite3')

    # Support absolute paths (e.g. Railway persistent volume /data/db_evaluation.sqlite3)
    db_path = Path(raw_db_name)
    if not db_path.is_absolute():
        db_path = BASE_DIR / db_path

    # Ensure parent directory exists for volume mounts
    try:
        db_path.parent.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

WHITENOISE_USE_FINDERS = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
