# Generated by Django 5.2.12 on 2026-03-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient_data', models.JSONField(help_text='JSON object with keys: gender, age, hypertension, heart_disease, smoking, bmi, HbA1c, glucose')),
                ('model_used', models.CharField(help_text="Name of the model used (e.g., 'DLNN Baseline', 'DLNN + Focal Loss')", max_length=100)),
                ('prediction', models.IntegerField(help_text='Binary prediction: 0 = Not Diabetic, 1 = Diabetic')),
                ('confidence', models.FloatField(help_text='Model confidence (probability), 0.0 to 1.0')),
                ('threshold', models.FloatField(default=0.5, help_text='Classification threshold used for this prediction')),
                ('shap_values', models.JSONField(blank=True, help_text='Per-feature SHAP contribution values as JSON', null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor_name', models.CharField(help_text='Name of the reviewing doctor/expert', max_length=200)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], help_text="Doctor's decision: accept or reject the AI prediction", max_length=10)),
                ('override_value', models.IntegerField(blank=True, help_text="If rejected, the doctor's corrected prediction (0 or 1)", null=True)),
                ('reason', models.TextField(blank=True, help_text="Doctor's reason for their decision (required for rejections)")),
                ('flagged_features', models.JSONField(blank=True, help_text='List of feature names the doctor flagged as unreliable/incorrect', null=True)),
                ('prediction', models.ForeignKey(help_text='The prediction this override relates to', on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='predictor.prediction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
