# Generated by Django 5.2.17 on 2026-09-04 15:25

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique anonymous screening record identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField(help_text='Participant age in years (18 to 80)')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Biological sex (male or female)', max_length=10)),
                ('bmi', models.DecimalField(decimal_places=1, help_text='Body Mass Index in kg/m² (11.1 to 69.9)', max_digits=4)),
                ('waist_cm', models.DecimalField(decimal_places=1, help_text='Waist circumference in cm (60.0 to 187.0)', max_digits=4)),
                ('hypertension_history', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Doctor-diagnosed hypertension history (yes or no)', max_length=5)),
                ('smoking_history', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='Smoking history: ≥100 cigarettes lifetime (yes or no)', max_length=5)),
                ('sedentary_minutes_day', models.PositiveSmallIntegerField(help_text='Typical daily sedentary time in minutes/day (0 to 1200)')),
                ('screening_probability', models.FloatField(help_text='Stage-1 screening probability at full 64-bit precision (0.0 to 1.0)')),
                ('ai_referral_recommended', models.BooleanField(help_text='True if screening_probability >= decision_threshold (0.1389)')),
                ('decision_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.1389'), help_text='Locked research decision threshold (0.1389)', max_digits=6)),
                ('model_name', models.CharField(default='Phase-5 GAM (λ=10.0, Splines=10)', help_text='Canonical model specification name', max_length=100)),
                ('model_sha256', models.CharField(default='204a94ff072ef4f1edecebf5a643738c006bbf010f3817b4bb798d3ea6fef41d', help_text='SHA-256 checksum of gam_final.pkl', max_length=64)),
                ('preprocessor_sha256', models.CharField(default='6e56a01993a4a6971eb62c82699c49da6f31a3acec2a1169e07862409f42824d', help_text='SHA-256 checksum of preprocessor.pkl', max_length=64)),
                ('input_schema_version', models.CharField(default='1.0', help_text='Version of Stage-1 input schema contract', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of screening record creation')),
                ('idempotency_token', models.CharField(blank=True, help_text='Token preventing accidental duplicate submission', max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='predictor_s_created_5b1290_idx'), models.Index(fields=['idempotency_token'], name='predictor_s_idempot_125c78_idx')],
            },
        ),
    ]
