# Generated by Django 5.2.17 on 2026-09-04 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_screeningrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique explanation record identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('method', models.CharField(default='gam_native_additive', help_text="Method used for explanation ('gam_native_additive')", max_length=50)),
                ('method_version', models.CharField(default='1.0', help_text='Version of explanation method contract', max_length=20)),
                ('link_function', models.CharField(default='logit', help_text="Link function on which additive terms are defined ('logit')", max_length=20)),
                ('intercept', models.FloatField(help_text='Frozen GAM model intercept (β0) on logit scale')),
                ('contributions_json', models.JSONField(help_text='JSON list of 7 feature contribution dicts')),
                ('reconstructed_linear_predictor', models.FloatField(help_text='Reconstructed sum of intercept and all feature contributions (η_recon)')),
                ('reconstructed_probability', models.FloatField(help_text='Reconstructed screening probability via inverse logit: σ(η_recon)')),
                ('reconstruction_error', models.FloatField(help_text='Absolute reconstruction error: |reconstructed_probability - screening_probability|')),
                ('model_sha256', models.CharField(default='204a94ff072ef4f1edecebf5a643738c006bbf010f3817b4bb798d3ea6fef41d', help_text='SHA-256 checksum of gam_final.pkl at explanation time', max_length=64)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', help_text='Explanation generation status', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='', help_text="Failure diagnostic if status == 'failed'")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of explanation creation')),
                ('screening_record', models.OneToOneField(help_text='Parent screening record explained by this decomposition', on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='predictor.screeningrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
