# Generated by Django 5.2.17 on 2026-09-04 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_screeningexplanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique anonymous review identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('reviewer_code', models.CharField(help_text='Anonymous study-safe reviewer identifier (e.g. R001, HP-03)', max_length=32)),
                ('review_action', models.CharField(choices=[('accepted', 'Accepted Recommendation')], default='accepted', help_text="Reviewer action: for Phase D2.6, strictly 'accepted'", max_length=20)),
                ('final_referral_recommended', models.BooleanField(help_text='Final referral decision derived server-side from AI recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of review submission')),
                ('screening_record', models.OneToOneField(help_text='Parent screening record reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='human_review', to='predictor.screeningrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
