# Generated by Django 5.2.17 on 2026-09-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_humanreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanreview',
            name='override_note',
            field=models.TextField(blank=True, help_text='Optional brief contextual rationale (max 500 chars; required if reason is Other)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='humanreview',
            name='override_reason_code',
            field=models.CharField(blank=True, help_text='Structured rationale category for override (required if overridden)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='humanreview',
            name='final_referral_recommended',
            field=models.BooleanField(help_text='Final referral decision derived server-side'),
        ),
        migrations.AlterField(
            model_name='humanreview',
            name='review_action',
            field=models.CharField(choices=[('accepted', 'Accepted Recommendation'), ('overridden', 'Overridden Recommendation')], help_text="Reviewer action: explicitly 'accepted' or 'overridden'", max_length=20),
        ),
        migrations.AlterField(
            model_name='humanreview',
            name='screening_record',
            field=models.OneToOneField(help_text='Parent screening record reviewed', on_delete=django.db.models.deletion.PROTECT, related_name='human_review', to='predictor.screeningrecord'),
        ),
    ]
