# Generated by Django 5.2.17 on 2026-09-04 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_humanreview_override_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage2Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique anonymous Stage-2 assessment identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('hba1c_percent', models.DecimalField(decimal_places=2, help_text='Entered HbA1c percentage (e.g. 5.70, 6.50)', max_digits=4)),
                ('laboratory_range', models.CharField(choices=[('normal_range', 'Normal-range'), ('prediabetes_range', 'Prediabetes-range'), ('diabetes_range', 'Diabetes-range')], help_text='Server-derived laboratory range category', max_length=32)),
                ('range_rule_version', models.CharField(default='ADA_2026_A1C_RANGE_V1', help_text='Frozen reference rule version identifier', max_length=64)),
                ('entry_method', models.CharField(default='manual', help_text='Provenance entry method (e.g. manual)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of Stage-2 assessment confirmation')),
                ('human_review', models.OneToOneField(help_text='Parent finalized HumanReview that authorized this Stage-2 assessment', on_delete=django.db.models.deletion.PROTECT, related_name='stage2_assessment', to='predictor.humanreview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
