# Generated by Django 5.2.17 on 2026-09-17 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_feedback_learning_loop'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(choices=[('session_started', 'Session Started'), ('practice_started', 'Practice Started'), ('practice_completed', 'Practice Completed'), ('stage1_completed', 'Stage 1 Completed'), ('xai_viewed', 'XAI Explanation Viewed'), ('human_review_completed', 'Human Review Completed'), ('override_recorded', 'Override Recorded'), ('stage2_completed', 'Stage 2 Completed'), ('feedback_submitted', 'Feedback Submitted'), ('questionnaire_started', 'Questionnaire Started'), ('questionnaire_submitted', 'Questionnaire Submitted'), ('session_completed', 'Session Completed')], max_length=50)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRespondent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respondent_code', models.CharField(help_text='Anonymous participant tracking code (e.g. RESP-xxxx)', max_length=50, unique=True)),
                ('age_group', models.CharField(choices=[('18-24', '18 – 24 tahun'), ('25-34', '25 – 34 tahun'), ('35-49', '35 – 49 tahun'), ('50+', '50 tahun ke atas')], max_length=20)),
                ('education_level', models.CharField(choices=[('high_school', 'SMA / SMK / Sederajat'), ('undergrad', 'Sarjana Terapan / Mahasiswa S1'), ('bachelor', 'Lulusan Sarjana (S1 / D4)'), ('postgrad', 'Magister (S2) / Spesialis / Doktoral (S3)')], max_length=20)),
                ('technical_background', models.CharField(choices=[('none', 'Tidak pernah / Belum pernah'), ('occasional', 'Kadang-kadang (1–2 kali per bulan)'), ('frequent', 'Sering / Rutin (mingguan atau harian)')], max_length=20)),
                ('health_background', models.CharField(choices=[('none', 'Tidak memiliki latar belakang bidang kesehatan'), ('student', 'Mahasiswa rumpun ilmu kesehatan (Kedokteran, Keperawatan, Gizi, Farmasi, Kesmas)'), ('practitioner', 'Tenaga kesehatan / Dokter / Praktisi klinis aktif')], max_length=20)),
                ('consent_given', models.BooleanField(default=True)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('app_version', models.CharField(default='research-prototype-v1.0', max_length=50)),
                ('model_version', models.CharField(default='GAM-v1', max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('practice_completed', models.BooleanField(default=False)),
                ('questionnaire_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_version', models.CharField(default='research-prototype-v1.0', max_length=50)),
                ('model_version', models.CharField(default='GAM-v1', max_length=50)),
                ('c1_answer', models.CharField(max_length=5)),
                ('c2_answer', models.CharField(max_length=5)),
                ('c3_answer', models.CharField(max_length=5)),
                ('c4_answer', models.CharField(max_length=5)),
                ('c5_answer', models.CharField(max_length=5)),
                ('c6_answer', models.CharField(max_length=5)),
                ('c7_answer', models.CharField(max_length=5)),
                ('c8_answer', models.CharField(max_length=5)),
                ('comprehension_score', models.PositiveSmallIntegerField(help_text='Count of correct comprehension answers (0 to 8)')),
                ('comprehension_pct', models.FloatField(help_text='Comprehension percentage: (score / 8) * 100')),
                ('sus_1', models.PositiveSmallIntegerField()),
                ('sus_2', models.PositiveSmallIntegerField()),
                ('sus_3', models.PositiveSmallIntegerField()),
                ('sus_4', models.PositiveSmallIntegerField()),
                ('sus_5', models.PositiveSmallIntegerField()),
                ('sus_6', models.PositiveSmallIntegerField()),
                ('sus_7', models.PositiveSmallIntegerField()),
                ('sus_8', models.PositiveSmallIntegerField()),
                ('sus_9', models.PositiveSmallIntegerField()),
                ('sus_10', models.PositiveSmallIntegerField()),
                ('sus_score', models.FloatField(help_text='Standardized System Usability Scale score (0.0 to 100.0)')),
                ('clarity_1', models.PositiveSmallIntegerField()),
                ('clarity_2', models.PositiveSmallIntegerField()),
                ('clarity_3', models.PositiveSmallIntegerField()),
                ('clarity_4', models.PositiveSmallIntegerField()),
                ('clarity_5', models.PositiveSmallIntegerField()),
                ('open_1', models.TextField(blank=True, default='', help_text='OQ1: Bagian paling membantu')),
                ('open_2', models.TextField(blank=True, default='', help_text='OQ2: Bagian paling membingungkan')),
                ('open_3', models.TextField(blank=True, default='', help_text='OQ3: Saran perbaikan utama')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='humanfeedback',
            new_name='predictor_h_is_elig_ee3742_idx',
            old_name='predictor_hf_eligible_idx',
        ),
        migrations.RenameIndex(
            model_name='humanfeedback',
            new_name='predictor_h_learnin_bbedb1_idx',
            old_name='predictor_hf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='humanfeedback',
            new_name='predictor_h_structu_8ec973_idx',
            old_name='predictor_hf_category_idx',
        ),
        migrations.RenameIndex(
            model_name='modelversion',
            new_name='predictor_m_is_acti_47e215_idx',
            old_name='predictor_m_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='modelversion',
            new_name='predictor_m_version_bce4ce_idx',
            old_name='predictor_m_version_idx',
        ),
        migrations.AddField(
            model_name='screeningrecord',
            name='is_practice',
            field=models.BooleanField(default=False, help_text='True if record is from onboarding practice case P0 (excluded from research analysis and learning)'),
        ),
        migrations.AlterField(
            model_name='feedbacklearningbatch',
            name='candidate_version',
            field=models.ForeignKey(blank=True, help_text='Candidate ModelVersion produced by this batch (null if training not yet done)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_batches_as_candidate', to='predictor.modelversion'),
        ),
        migrations.AlterField(
            model_name='feedbacklearningbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of batch completion (activation, rejection, or failure)', null=True),
        ),
        migrations.AlterField(
            model_name='feedbacklearningbatch',
            name='validation_metrics',
            field=models.JSONField(blank=True, help_text='Validation metrics for the candidate version (feedback-experiment metrics only)', null=True),
        ),
        migrations.AlterField(
            model_name='humanfeedback',
            name='feedback_direction',
            field=models.CharField(help_text='Learning direction: reduce_influence, increase_influence, contextual_adjustment, reduce_global, increase_global, no_learning', max_length=30),
        ),
        migrations.AlterField(
            model_name='humanfeedback',
            name='nlp_confidence',
            field=models.FloatField(blank=True, help_text='NLP classification confidence [0, 1] (null if no free-text provided)', null=True),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='predictor.evaluationrespondent'),
        ),
        migrations.AddField(
            model_name='evaluationevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='predictor.evaluationsession'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='predictor.evaluationrespondent'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_response', to='predictor.evaluationsession'),
        ),
    ]
