# Generated by Django 5.2.17 on 2026-09-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_evaluationevent_evaluationrespondent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningrecord',
            name='bmi',
            field=models.DecimalField(decimal_places=2, help_text='Body Mass Index in kg/m² (11.1 to 69.9)', max_digits=5),
        ),
    ]
